stages:
  - build
  - deploy
  - test

dev-build:
  stage: build
  only:
    - main
  script:
    - echo "dev build"

dev-deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "dev deploy"

dev-test:
  stage: test
  only:
    - main
  script:
    - echo "dev testing"